"""Init

Revision ID: d530fd23930b
Revises:
Create Date: 2026-09-25 18:03:18.142054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd530fd23930b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('research_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('research_depth', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('require_plan_approval', sa.Boolean(), nullable=False),
    sa.Column('max_sources', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('budget_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('report_length', sa.String(length=20), nullable=False),
    sa.Column('citation_style', sa.String(length=20), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_research_tasks_user_id'), 'research_tasks', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('workflow_version', sa.String(length=50), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_research_task_id'), 'agent_runs', ['research_task_id'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('export_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_artifacts_research_task_id'), 'export_artifacts', ['research_task_id'], unique=False)
    op.create_table('research_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=30), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_claims_research_task_id'), 'research_claims', ['research_task_id'], unique=False)
    op.create_table('research_iterations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('iteration_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('queries_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources_found', sa.Integer(), nullable=False),
    sa.Column('chunks_indexed', sa.Integer(), nullable=False),
    sa.Column('critic_verdict', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_iterations_research_task_id'), 'research_iterations', ['research_task_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_research_task_id'), 'research_reports', ['research_task_id'], unique=True)
    op.create_table('research_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('source_tag', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_task_id'), 'research_sources', ['research_task_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('citation_label', sa.String(length=20), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('chunk_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_claim_id'), 'citations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_citations_report_id'), 'citations', ['report_id'], unique=False)
    op.create_index(op.f('ix_citations_source_id'), 'citations', ['source_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_research_task_id'), 'document_chunks', ['research_task_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_id'), 'document_chunks', ['source_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_agent_run_id'), 'evaluations', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_evaluations_research_task_id'), 'evaluations', ['research_task_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_task_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_chunk_id'), 'evidences', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_evidences_research_task_id'), 'evidences', ['research_task_id'], unique=False)
    op.create_index(op.f('ix_evidences_source_id'), 'evidences', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_source_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_research_task_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_chunk_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_evaluations_research_task_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_agent_run_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_document_chunks_source_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_research_task_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_citations_source_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_report_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_claim_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_research_sources_research_task_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_reports_research_task_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_iterations_research_task_id'), table_name='research_iterations')
    op.drop_table('research_iterations')
    op.drop_index(op.f('ix_research_claims_research_task_id'), table_name='research_claims')
    op.drop_table('research_claims')
    op.drop_index(op.f('ix_export_artifacts_research_task_id'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index(op.f('ix_agent_runs_research_task_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_research_tasks_user_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_status'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
